# Generated by Django 6.0.3 on 2026-04-12 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0024_remove_employeeleave_hr_delivered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'Morning Shift'), ('middle', 'Middle Shift'), ('night', 'Night Shift')], default='morning', max_length=20)),
                ('check_in_at', models.DateTimeField(blank=True, null=True)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('check_in_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_location_label', models.CharField(blank=True, default='', max_length=255)),
                ('check_out_location_label', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_events', to='employees.employee')),
                ('synced_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='self_service_events', to='employees.employeeattendanceledger')),
            ],
            options={
                'ordering': ['-attendance_date', '-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'attendance_date'), name='unique_employee_attendance_event_date')],
            },
        ),
    ]
