# Generated by Django 6.0.3 on 2026-04-12 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_employeeattendanceevent'),
        ('organization', '0008_alter_branch_image_alter_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchWeeklyScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True)),
                ('schedule_date', models.DateField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('shift_label', models.CharField(blank=True, max_length=100)),
                ('order_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='planned', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedule_entries', to='organization.branch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_weekly_schedule_entries', to='employees.employee')),
            ],
            options={
                'ordering': ['schedule_date', 'employee__full_name', 'title', 'id'],
            },
        ),
    ]
