# Generated by Django 6.0.3 on 2026-04-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0026_branchweeklyscheduleentry'),
        ('organization', '0008_alter_branch_image_alter_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchweeklyscheduleentry',
            name='duty_type',
            field=models.CharField(choices=[('shift', 'Shift'), ('off', 'Off'), ('extra_off', 'Extra Off'), ('custom', 'Custom Duty')], default='shift', max_length=20),
        ),
        migrations.AddField(
            model_name='branchweeklyscheduleentry',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branchweeklyscheduleentry',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branchweeklyscheduleentry',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='branchweeklyscheduleentry',
            unique_together={('branch', 'employee', 'schedule_date')},
        ),
    ]
