# Generated by Django 6.0.3 on 2026-04-12 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0027_branchweeklyscheduleentry_duty_type_and_more'),
        ('organization', '0008_alter_branch_image_alter_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchWeeklyDutyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('duty_type', models.CharField(choices=[('shift', 'Shift'), ('off', 'Off'), ('extra_off', 'Extra Off'), ('custom', 'Custom Duty')], default='shift', max_length=20)),
                ('default_start_time', models.TimeField(blank=True, null=True)),
                ('default_end_time', models.TimeField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_duty_options', to='organization.branch')),
            ],
            options={
                'ordering': ['display_order', 'label', 'id'],
                'unique_together': {('branch', 'label')},
            },
        ),
        migrations.AddField(
            model_name='branchweeklyscheduleentry',
            name='duty_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries', to='employees.branchweeklydutyoption'),
        ),
        migrations.CreateModel(
            name='BranchWeeklyPendingOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True)),
                ('pending_off_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_pending_off_records', to='organization.branch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_pending_off_records', to='employees.employee')),
            ],
            options={
                'ordering': ['week_start', 'employee__full_name', 'id'],
                'unique_together': {('branch', 'employee', 'week_start')},
            },
        ),
    ]
