# Generated by Django 6.0.3 on 2026-04-12 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0028_branchweeklydutyoption_and_more'),
        ('organization', '0008_alter_branch_image_alter_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchScheduleGridCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_index', models.PositiveSmallIntegerField()),
                ('value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_grid_cells', to='organization.branch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_grid_cells', to='employees.employee')),
            ],
            options={
                'ordering': ['employee__full_name', 'column_index', 'id'],
                'unique_together': {('branch', 'employee', 'column_index')},
            },
        ),
    ]
