# Generated by Django 6.0.3 on 2026-04-12 22:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0008_alter_branch_image_alter_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audience', models.CharField(choices=[('all', 'All Users'), ('employees', 'Employees'), ('management', 'Management'), ('hr', 'HR Team')], default='all', max_length=30)),
                ('message', models.TextField()),
                ('published_at', models.DateField(default=django.utils.timezone.localdate)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HR Announcement',
                'verbose_name_plural': 'HR Announcements',
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HRPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('policy', 'Policy'), ('benefit', 'Benefit'), ('compliance', 'Compliance'), ('onboarding', 'Onboarding')], default='policy', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('effective_date', models.DateField(default=django.utils.timezone.localdate)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_policies', to='organization.company')),
            ],
            options={
                'verbose_name': 'HR Policy',
                'verbose_name_plural': 'HR Policies',
                'ordering': ['title'],
            },
        ),
    ]
