# Generated by Django 6.0.3 on 2026-04-13 20:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0030_branchschedulegrid_layout'),
        ('organization', '0008_alter_branch_image_alter_company_logo'),
        ('payroll', '0002_payrolladjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('obligation_type', models.CharField(choices=[('loan', 'Loan'), ('advance', 'Advance')], max_length=20)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_installments', models.PositiveIntegerField(default=1)),
                ('paid_installments', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('hold', 'On Hold')], default='active', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_obligations', to='organization.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_obligations', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Payroll Obligation',
                'verbose_name_plural': 'Payroll Obligations',
                'ordering': ['employee__full_name', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payrolladjustment',
            name='payroll_obligation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_adjustments', to='payroll.payrollobligation'),
        ),
    ]
